# Generated by Django 5.2.5 on 2025-10-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='textarea',
            new_name='content',
        ),
    ]
