# Generated by Django 5.2.5 on 2025-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followStatus',
            field=models.BooleanField(default=False),
        ),
    ]
